version: '3.1'

services:
  db:
    image: postgis/postgis:13-master
    environment:
      POSTGRES_DB: souraiko
      POSTGRES_USER: souraiko
      POSTGRES_PASSWORD: souraiko
    ports:
      - '5432:5432'
  # redis:
  #   image: redis
  #   ports:
  #     - '6379:6379'
