version: '3.1'

services:
  db:
    image: postgis/postgis:15-master
    environment:
      POSTGRES_DB: some_db
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: some_password
    ports:
      - '5432:5432'
